/**
 * Lego slot wiring + config — GENERATED by _legos_config_generator.py
 * at substrate install time. DO NOT hand-edit.
 *
 * Spec authority: NEXUS_PORTFOLIO_RUNTIME_SPEC.md §4.4.
 */

export interface LegoSlot {
  readonly name: string;
  readonly contract: string;
  readonly description?: string;
}

export interface LegoConfig {
  readonly name: string;
  readonly version: string;
  readonly isStub: boolean;
  readonly slots: readonly LegoSlot[];
  readonly config: Record<string, unknown>;
}

export const LEGOS: readonly LegoConfig[] = [
  {
    "config": {
      "enable_feature_flags": true,
      "enable_impersonation": false
    },
    "isStub": false,
    "name": "admin-console",
    "slots": [
      {
        "contract": "react-component",
        "description": "Extra navigation items injected into the admin sidebar by other legos.",
        "name": "admin_nav_extra"
      },
      {
        "contract": "react-component",
        "description": "Widgets contributed to the admin dashboard overview page.",
        "name": "admin_dashboard_widgets"
      },
      {
        "contract": "react-component",
        "description": "Per-row action buttons injected into the admin users table (e.g. Identity & Access \"force delete\" / \"revoke sessions\").",
        "name": "admin_user_actions"
      }
    ],
    "version": "0.1.0"
  },
  {
    "config": {
      "funnels": []
    },
    "isStub": false,
    "name": "analytics-and-telemetry",
    "slots": [
      {
        "contract": "react-component",
        "description": "Metrics dashboard widget (funnels + key counts).",
        "name": "analytics_dashboard"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "default_currency": "usd",
      "enable_proration": true,
      "trial_days": 0
    },
    "isStub": false,
    "name": "billing-and-subscriptions",
    "slots": [
      {
        "contract": "react-component",
        "description": "Extra form fields injected into the checkout flow (e.g., promo code, referral source).",
        "name": "checkout_extra_fields"
      },
      {
        "contract": "server-hook",
        "description": "Server-side hook to redirect after successful subscription creation.",
        "name": "post_subscription_redirect"
      },
      {
        "contract": "react-component",
        "description": "Per-subscription metadata fields appended to the Stripe subscription record.",
        "name": "subscription_extra_metadata"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {},
    "isStub": false,
    "name": "crm-and-lifecycle",
    "slots": [
      {
        "contract": "react-component",
        "description": "Embeddable lead-capture form (name/email/source) for marketing pages. Posts to the lego's lead-capture API; the agent triages + scores on arrival.\n",
        "name": "lead_capture_form"
      },
      {
        "contract": "react-component",
        "description": "Contact detail sidebar (history + AI-proposed next action) shown on a contact record. Renders the agent's propose_next_action recommendation.\n",
        "name": "contact_sidebar"
      },
      {
        "contract": "server-hook",
        "description": "Server hook fired when a new lead is captured \u2014 triggers agent scoring + (optionally) an outreach draft. No-op when unconfigured.\n",
        "name": "after_lead_captured_hook"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {},
    "isStub": false,
    "name": "developer-surface",
    "slots": [
      {
        "contract": "react-component",
        "description": "API key management (create/rotate/revoke) for developers.",
        "name": "api_keys_panel"
      },
      {
        "contract": "react-component",
        "description": "Webhook endpoint management + delivery status.",
        "name": "webhooks_panel"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {},
    "isStub": false,
    "name": "files-and-media",
    "slots": [
      {
        "contract": "react-component",
        "description": "Drag-and-drop file upload widget with progress + scan status.",
        "name": "file_uploader"
      },
      {
        "contract": "react-component",
        "description": "User's file list with category + download.",
        "name": "file_list"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {},
    "isStub": false,
    "name": "identity-and-access",
    "slots": [
      {
        "contract": "react-component",
        "description": "Inject custom fields or UI elements above the standard email/password inputs on the signup form.\n",
        "name": "before_signup_fields"
      },
      {
        "contract": "react-component",
        "description": "Legal acknowledgment block shown at the bottom of the signup form. Defaults to a standard ToS + privacy placeholder; full email-linked template lands in 2.2.\n",
        "name": "signup_legal_acknowledgment"
      },
      {
        "contract": "server-hook",
        "description": "Server hook executed after a successful login to determine where to redirect the user. Falls back to /dashboard when not configured.\n",
        "name": "after_login_redirect"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "cookie_banner_enabled": true,
      "jurisdiction": "us",
      "liability_boundary_class": "assistant"
    },
    "isStub": false,
    "name": "legal-and-compliance",
    "slots": [
      {
        "contract": "react-component",
        "description": "Additional links injected into the site footer alongside the standard Terms / Privacy / Cookie Policy links. Other legos may inject their own compliance links here (e.g. sub-processor list, DPA download).\n",
        "name": "extra_legal_links"
      },
      {
        "contract": "server-hook",
        "description": "Addendum injected at the end of the Terms of Service document. Use for company-specific clauses that cannot go in the base template.\n",
        "name": "policy_addendum_terms_of_service"
      },
      {
        "contract": "server-hook",
        "description": "Addendum injected at the end of the Privacy Policy document.\n",
        "name": "policy_addendum_privacy_policy"
      },
      {
        "contract": "server-hook",
        "description": "Addendum injected at the end of the Cookie Policy document.\n",
        "name": "policy_addendum_cookie_policy"
      },
      {
        "contract": "server-hook",
        "description": "Addendum injected at the end of the Accessibility Statement document.\n",
        "name": "policy_addendum_accessibility_statement"
      }
    ],
    "version": "0.1.0"
  },
  {
    "config": {
      "contradiction_threshold": 3,
      "knowledge_compiler_debounce_seconds": 300,
      "long_term_eviction_no_retrieval_days": 90,
      "working_memory_ttl_days": 7
    },
    "isStub": false,
    "name": "memory-and-knowledge",
    "slots": [
      {
        "contract": "react-component",
        "description": "Admin-console pane showing per-company memory rows + tier badges",
        "name": "admin_memory_inspector"
      },
      {
        "contract": "react-component",
        "description": "User-facing GDPR export + forget-me controls",
        "name": "user_memory_export"
      }
    ],
    "version": "0.1.0"
  },
  {
    "config": {
      "default_channels": [
        "email",
        "in_app"
      ],
      "rate_limit_per_user_per_hour": 30
    },
    "isStub": false,
    "name": "notifications",
    "slots": [
      {
        "contract": "react-component",
        "description": "HTML injected at the top of every transactional email (logo, brand banner).",
        "name": "email_layout_header"
      },
      {
        "contract": "react-component",
        "description": "HTML injected at the bottom of every transactional email (legal footer, unsubscribe link).",
        "name": "email_layout_footer"
      },
      {
        "contract": "react-component",
        "description": "Per-row action buttons injected into the in-app inbox.",
        "name": "in_app_inbox_extra_actions"
      }
    ],
    "version": "0.1.0"
  },
  {
    "config": {
      "steps": [
        "verify_email",
        "complete_profile",
        "first_action",
        "invite_team"
      ]
    },
    "isStub": false,
    "name": "onboarding",
    "slots": [
      {
        "contract": "react-component",
        "description": "First-run checklist widget shown until onboarding completes.",
        "name": "onboarding_checklist"
      },
      {
        "contract": "react-component",
        "description": "Product tour overlay for the first session.",
        "name": "welcome_tour"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "roles": [
        "owner",
        "admin",
        "member",
        "viewer"
      ]
    },
    "isStub": false,
    "name": "organizations-and-teams",
    "slots": [
      {
        "contract": "react-component",
        "description": "Org switcher dropdown for the app shell (when a user belongs to >1 org).\n",
        "name": "org_switcher"
      },
      {
        "contract": "react-component",
        "description": "Members management table (role, seat, invite/remove) for org admins.\n",
        "name": "members_table"
      },
      {
        "contract": "server-hook",
        "description": "Server hook fired when a member accepts an invitation \u2014 used for onboarding + seat accounting. No-op when unconfigured.\n",
        "name": "after_member_joined_hook"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {},
    "isStub": false,
    "name": "profile-and-account",
    "slots": [
      {
        "contract": "react-component",
        "description": "The profile editor panel (display name, avatar, bio, timezone, preferences). Mounted in the account settings surface.\n",
        "name": "profile_settings_panel"
      },
      {
        "contract": "react-component",
        "description": "List of connected OAuth/identity providers with connect/disconnect.\n",
        "name": "connected_accounts_panel"
      },
      {
        "contract": "react-component",
        "description": "GDPR \"download my data\" button that requests an account export.\n",
        "name": "account_export_button"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "facets": [
        "entity_type",
        "category"
      ]
    },
    "isStub": false,
    "name": "search",
    "slots": [
      {
        "contract": "react-component",
        "description": "Global cmd+K search palette mounted in the app shell.",
        "name": "command_palette"
      },
      {
        "contract": "react-component",
        "description": "Faceted results panel with sort + pagination.",
        "name": "search_results_panel"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {},
    "isStub": false,
    "name": "social-and-engagement",
    "slots": [
      {
        "contract": "react-component",
        "description": "Comment thread component for any entity (post/product/etc).",
        "name": "comment_thread"
      },
      {
        "contract": "react-component",
        "description": "Reaction (like/etc) bar for an entity.",
        "name": "reaction_bar"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {},
    "isStub": false,
    "name": "support-and-help",
    "slots": [
      {
        "contract": "react-component",
        "description": "Floating launcher button injected into the substrate's app shell. Opens the in-app SupportWidget (KB search + new-ticket form + ticket history).\n",
        "name": "support_widget_launcher"
      },
      {
        "contract": "react-component",
        "description": "Nav/footer link to the company's help center / KB index. Renders nothing when the company has no published KB articles.\n",
        "name": "help_center_link"
      },
      {
        "contract": "server-hook",
        "description": "Server hook executed when a ticket transitions to resolved \u2014 used to trigger a CSAT feedback request via the notifications lego. No-op when unconfigured.\n",
        "name": "after_ticket_resolved_hook"
      }
    ],
    "version": "1.0.0"
  }
];

export function findSlotProvider(slotName: string): LegoConfig | undefined {
  return LEGOS.find((lego) =>
    lego.slots.some((slot) => slot.name === slotName),
  );
}
