/**
 * Top Navigation Configuration — GENERATED (nav-population-reliability-001).
 *
 * AUTO-GENERATED by the release pipeline from the (domain) route group's
 * top-level pages. DO NOT hand-edit — this file is regenerated on every
 * release. The substrate TopNav reads NAV_CONFIG.primary / NAV_CONFIG.groups.
 */

export type NavLink = {
  href: string;
  label: string;
};

export type NavGroup = {
  label: string;
  links: NavLink[];
};

export type NavConfig = {
  primary: NavLink[];
  groups: NavGroup[];
};

export const NAV_CONFIG: NavConfig = {
  primary: [
    { href: "/", label: "Home" },
    { href: "/accessibility", label: "Accessibility" },
    { href: "/cookie-policy", label: "Cookie Policy" },
    { href: "/privacy", label: "Privacy" },
    { href: "/terms", label: "Terms" },
  ],
  groups: [],
};
